apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-cfg
data:
  conf-file-from-cfgmap: |
    input:
     csv:
      paths: [/data/pipeline/data-file-from-cfgmap]
      parse_header_row: true
      delimiter: ','
      lazy_quotes: false

    output:
     stdout:
      codec: lines
